Planet_Homeostatic_Vector/
  README.md
  pyproject.toml
  .gitignore
  configs/
    run_tier1.yaml
  data/
    raw/
      exoplanets/        # place your NASA export here
    derived/
  docs/
    logbooks/
      PLANET_HOMEOSTASIS_RIPENESS_EXECUTION.tex
  scripts/
    00_setup_dirs.sh
    10_run_tier1.sh
  src/
    phv/
      __init__.py
      cli.py
      io/
        __init__.py
        exo_csv.py
      metrics/
        __init__.py
        proxies.py
        normalize.py
        window.py
        ripeness.py
      pipeline/
        __init__.py
        tier1.py
      utils/
        __init__.py
        logging.py
        hashing.py
  tests/
    test_window.py
    test_normalize.py
